import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReduxProvider } from "./ReduxProvider";
import Header from "@/components/header";
import Promo from "@/components/promo";
import { ttRunsRegular } from "./font";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Репетитораская империя",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${ttRunsRegular.variable} antialiased `}>
        <ReduxProvider>
          <Header />
          <Promo />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
